### ISSUE TITLE
AWS: Add logic to deal with trailing slashes in the bucket ARN within the `aws_cloudtrail` module

### ISSUE THREAD

**Issue by dm4r** [lacework/terraform-provisioning#102]
When defining the bucket ARN, it is easy to copy/paste it out of the AWS Console with a trailing slash included:
`arn:aws:s3:::aws-cloudtrail-logs/AWSLogs/999999999999/`

![image](https://user-images.githubusercontent.com/10539133/99028641-1d44d500-2525-11eb-88c6-8fd3da7395f1.png)

This results in the `aws_cloudtrail` Terraform module using the provided ARN and appending an additional trailing slash:
`          + resources = [
              + "arn:aws:s3:::aws-cloudtrail-logs/AWSLogs/999999999999//*",`

Which in turn results in malformed policy values captured in the `lacework_iam_role`, S3 Permissions:
```
GetObject
ObjectPath | string like | AWSLogs/999999999999//*, BucketName | string like | aws-cloudtrail-logs-999999999999-0abe6e44
```
**Note the double-slash as part of the generated policy value.**  

This malformed policy value results in a permissions issue error in the Lacework UI, CloudTrail Settings integration section (as per attached screenshot). 
![image](https://user-images.githubusercontent.com/10539133/99028501-c3dca600-2524-11eb-9c0b-c3d0f86d0cab.png)

**Comment by afiune** [comment]
Thank you for reporting this issue, this could be solved super quick with https://www.terraform.io/docs/configuration/functions/trimsuffix.html

cc @scottford-lw
