### ISSUE TITLE
AWS Docs: Example TF plan for environments using S3 Buckets w/Server-Side Encryption and AWS KMS-Managed Keys 

### ISSUE THREAD

**Issue by dm4r** [lacework/terraform-provisioning#103]
Could use a doc update to reflect an example plan of the necessary module inputs to integrate Lacework AWS CloudTrail analysis with S3 Buckets that are Using Server-Side Encryption with AWS KMS-Managed Keys.

The three key inputs necessary to accomplish this are:
```
bucket_enable_encryption = true
bucket_sse_algorithm     = "aws:kms"
bucket_sse_key_arn       = "InsertARN of the KMS encryption key to be used"
```

**Comment by afiune** [comment]
Done already!
