### ISSUE TITLE
aws_config module misconfigured/broken for older versions. Min version should be 0.12.26

### ISSUE THREAD

**Issue by red8888** [lacework/terraform-provisioning#106]
your module has the wrong version pinned: 

```
terraform {
  required_version = ">= 0.12.0" 
  # please change to ">= 0.12.26"

  required_providers {
    aws    = "~> 3.0"
    random = ">= 2.1"
    time   = "~> 0.6"
      # 0.12.0  does NOT support this
    lacework = {
      source  = "lacework/lacework"
      version = "~> 0.2"
    }
  }
}
```

The docs make this clear: https://www.terraform.io/docs/configuration/provider-requirements.html#v0-12-compatible-provider-requirements

I get an error message `line 8: Unsuitable value: string`

I should be getting a message saying I need at least version 0.12.26 because your module is mixing 0.12 and 0.13 syntax

**Comment by scottford-lw** [comment]
@red8888 Thanks so much for pointing this out! This project has been deprecated. We have migrated all of the Lacework Terraform modules to the [Terraform Registry](https://registry.terraform.io/providers/lacework/lacework/latest) 🙌 . Additionally, we have updated the docs on support.lacework.com to reflect the changes you suggested. Please take a look at this doc if you have a minute...

https://support.lacework.com/hc/en-us/articles/360061585353-Terraform-for-Lacework-Overview

Lastly, all of the individual docs on using these modules for AWS, GCP, or Azure have been updated to require at least Terraform `0.12.26`

Again, thanks for pointing this out!
