### ISSUE TITLE
tokenizing integration name from project id, tenant id, aws account

### ISSUE THREAD

**Issue by afiune** [lacework/terraform-provisioning#89]
Could we guess the integration name from the project id, tenant id, or aws account we are integrating?

**Comment by rylad** [comment]
To add some color, currently - when doing a project level organization across numerous projects, you need to introduce uniqueness and modify the terraform code. That then requires changing certain lines across each file. If we could leverage one of these fields as a prefix vs the predefined, that might avoid a lot of issues.

**Azure Specific** - when doing azure, we had an issue with the l4c3work storage user, as the storage user has to be azure unique. We over rode that with the customer specific prefix, and that resolved that - however, this is an optional step. I imagine most people will hit this issue when doing azure terraform deploys.

**Comment by afiune** [comment]
@rylad Thank you so much for your feedback. We have added a unique suffix to every resource for Azure https://github.com/lacework/terraform-azure-activity-log/pull/1 (as well as GCP) which should help a lot with the issue of name collision. 🎉

Additionally, we have successfully migrated our Terraform modules to the Terraform Registry, we recently updated the README.md to reflect the fact that we are deprecating this repository in favor of such modules. https://github.com/lacework/terraform-provisioning#warning---this-project-is-being-deprecated 

This migration allows you to use Terraform 13 that introduced the `for_each` argument to modules! 🙌🏽

We haven't documented this use case but, hypothetically you should be able to do a Project Level integration of multiple projects with a Terraform code similar to this one:
```hcl
variable projects {
  type        = list(string)
  default     = ["project_id_1", "project_id_2", "project_id_300"]
}

provider "google" {}

module "config" {
  source     = "lacework/config/gcp"
  version    = "~> 0.1.0"
  for_each   = var.projects
  project_id = each.value
}
module "audit_log" {
    source  = "lacework/audit-log/gcp"
    version = "~> 0.1.0"

    bucket_force_destroy         = true
    use_existing_service_account = true

    for_each   = var.projects
    project_id = each.value
    service_account_name         = module.config[each.key].service_account_name
    service_account_private_key  = module.config[each.key] service_account_private_key
}
```

We will be working on adding this documentation to https://support.lacework.com/hc/en-us/search?utf8=%E2%9C%93&query=terraform

**Comment by dmurray-lacework** [comment]
Closing as this project is deprecated
